import { Translations, LanguageCode, TranslationDict } from '@/types';

export const DICTIONARY: Translations = {
  en: {
    appName: 'WorldExplorer',
    tagline: 'Discover the world with data, flags, and beautiful insights.',
    searchPlaceholder: 'Search for a country by name, capital...',
    allRegions: 'All Regions',
    region: 'Region',
    population: 'Population',
    capital_label: 'Capital',
    favorites: 'Favorites',
    noFavorites: 'You haven\'t added any countries to your favorites yet. Start exploring!',
    addFavorite: 'Add to Favorites',
    removeFavorite: 'Remove from Favorites',
    backHome: 'Back to Countries',
    sortBy: 'Sort by',
    sortNameAsc: 'Name (A-Z)',
    sortNameDesc: 'Name (Z-A)',
    sortPopAsc: 'Population (Low - High)',
    sortPopDesc: 'Population (High - Low)',
    sortAreaAsc: 'Area (Smaller - Larger)',
    sortAreaDesc: 'Area (Larger - Smaller)',
    subregion: 'Subregion',
    languages: 'Languages',
    currencies: 'Currencies',
    area_label: 'Area',
    borders: 'Border Countries',
    noBorders: 'No border countries',
    mapLink: 'View on Google Maps',
    errorLoading: 'An error occurred while loading public data.',
    tryAgain: 'Try Again',
    loading: 'Loading countries data, please wait...',
    countriesCount: 'countries found',
    timezones: 'Timezones',
    nativeName: 'Native Name',
  },
  uz: {
    appName: 'WorldExplorer',
    tagline: 'Dunyo mamlakatlarini ma’lumotlar, bayroqlar va chiroyli tahlillar bilan oling.',
    searchPlaceholder: 'Mamlakat yoki poytaxt nomini qidiring...',
    allRegions: 'Barcha hududlar',
    region: 'Mintaqa',
    population: 'Aholi soni',
    capital_label: 'Poytaxt',
    favorites: 'Sevimlilar',
    noFavorites: 'Siz hali sevimli mamlakatlar ro‘yxatiga hech narsa qo‘shmadingiz. Izlashni boshlang!',
    addFavorite: 'Sevimlilarga qo‘shish',
    removeFavorite: 'Sevimlilardan o‘chirish',
    backHome: 'Mamlakatlarga qaytish',
    sortBy: 'Saralash',
    sortNameAsc: 'Nomi (A-Z)',
    sortNameDesc: 'Nomi (Z-A)',
    sortPopAsc: 'Aholi soni (Kamdan - Ko‘pga)',
    sortPopDesc: 'Aholi soni (Ko‘pdan - Kamga)',
    sortAreaAsc: 'Maydoni (Kichikdan - Kattaga)',
    sortAreaDesc: 'Maydoni (Kattadan - Kichikka)',
    subregion: 'Submintaqa',
    languages: 'Tillar',
    currencies: 'Valyutalar',
    area_label: 'Maydoni',
    borders: 'Chegaradosh davlatlar',
    noBorders: 'Chegaradosh davlatlar mavjud emas',
    mapLink: 'Google xaritada ko‘rish',
    errorLoading: 'Ma’lumotlarni yuklashda xatolik yuz berdi.',
    tryAgain: 'Qayta urinish',
    loading: 'Mamlakatlar ma’lumotlari yuklanmoqda, iltimos kuting...',
    countriesCount: 'mamlakat topildi',
    timezones: 'Vaqt mintaqalari',
    nativeName: 'Asl nomi',
  },
  ru: {
    appName: 'WorldExplorer',
    tagline: 'Откройте для себя мир с данными, флагами и красивой статистикой.',
    searchPlaceholder: 'Поиск страны по названию, столице...',
    allRegions: 'Все регионы',
    region: 'Регион',
    population: 'Население',
    capital_label: 'Столица',
    favorites: 'Избранное',
    noFavorites: 'Вы еще не добавили ни одной страны в избранное. Начните исследовать!',
    addFavorite: 'Добавить в избранное',
    removeFavorite: 'Удалить из избранного',
    backHome: 'Назад к странам',
    sortBy: 'Сортировка',
    sortNameAsc: 'Название (А-Я)',
    sortNameDesc: 'Название (Я-А)',
    sortPopAsc: 'Население (Возрастание)',
    sortPopDesc: 'Население (Убывание)',
    sortAreaAsc: 'Площадь (Возрастание)',
    sortAreaDesc: 'Площадь (Убывание)',
    subregion: 'Субрегион',
    languages: 'Языки',
    currencies: 'Валюты',
    area_label: 'Площадь',
    borders: 'Граничащие страны',
    noBorders: 'Нет граничащих стран',
    mapLink: 'Посмотреть на Google Картах',
    errorLoading: 'Произошла ошибка при загрузке данных.',
    tryAgain: 'Попробовать снова',
    loading: 'Загрузка данных о странах, пожалуйста, подождите...',
    countriesCount: 'стран найдено',
    timezones: 'Часовые пояса',
    nativeName: 'Местное название',
  },
};

export function formatNumber(num: number | undefined): string {
  if (num === undefined) return 'N/A';
  return new Intl.NumberFormat().format(num);
}

export function formatArea(area: number | undefined): string {
  if (area === undefined) return 'N/A';
  return `${formatNumber(area)} km²`;
}

export function getTranslation(key: keyof TranslationDict, lang: LanguageCode): string {
  const dictionary = DICTIONARY[lang] || DICTIONARY['en'];
  return dictionary[key] || DICTIONARY['en'][key] || '';
}
